version: "3.7"

services:
  backend:
    container_name: backend
    image: kdh92417/zium-backend:latest
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.local
    env_file:
      - .env
    ports:
      - "8000:8000"
