version: "3.7"

services:
  mysql:
    container_name: mysql
    build: ./mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --range_optimizer_max_mem_size=16777216
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    networks:
      - local-net

  backend:
    container_name: backend
    build: ./backend
    restart: always
    volumes:
      - ./backend:/backend
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.local
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
