version: "3.7"

services:
  backend:
    container_name: backend
    build: ./backend
    restart: always
    volumes:
      - ./backend:/backend
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.local
    env_file:
      - .env
    ports:
      - "8000:8000"
