name: Build and Deploy in EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and push to DockerHub
      env:
        REPO: kdh92417
        LAYER_NAME: zium-backend
      run: |
        ls -al
        docker build -t $LAYER_NAME  ./backend
        docker tag $LAYER_NAME:latest $REPO/$LAYER_NAME:latest
        docker push $REPO/$LAYER_NAME:latest
        
    - uses: actions/checkout@v2
    - name: restart
      env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOST_NAME : ${{ secrets.HOST  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
          cd /home/ubuntu/zium &&
          sudo docker-compose down &&
          sudo docker-compose -f docker-compose.prod.yml up -d
        '
